workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

include:
  - component: $CI_SERVER_FQDN/composants/dart/format@0.0.10
  - component: $CI_SERVER_FQDN/composants/dart/analyze@0.0.10
  - component: $CI_SERVER_FQDN/composants/dart/fix@0.0.10
  - component: $CI_SERVER_FQDN/composants/dart/test@0.0.10
  - component: $CI_SERVER_FQDN/composants/dart/coverage@0.0.10
  - component: $CI_SERVER_FQDN/composants/dart/pana@0.0.10
  - component: $CI_SERVER_FQDN/composants/dart/doc@0.0.10

stages:
  - format
  - analyze
  - fix
  - test
  - coverage
  - pana
  - doc
  - release

# If the pipeline is for a new tag with a semantic version, and all previous jobs succeed,
# create the release.
create-release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script: echo "Creating release $CI_COMMIT_TAG"
  rules:
    - if: $CI_COMMIT_TAG
  release:
    tag_name: $CI_COMMIT_TAG
    description: "Release $CI_COMMIT_TAG of components repository $CI_PROJECT_PATH"
